fix broken build: constrain sequelize <6.14.0
Constrain sequelize to versions earlier than [6.14.0][sequelize 6.14.0],
because that version made this change:

> * **types:** drop TypeScript < 4.1 (#13954) (dd49044)

which breaks `npm run build-types` (and thus `npm run build`) in this project,
making them emit a bunch of TypeScript errors such as:

```
node_modules/sequelize/dist/lib/model.d.ts:3032:19 - error TS1005: ']' expected.

3032   [Key in keyof M as
                       ~~

node_modules/sequelize/dist/lib/model.d.ts:3033:12 - error TS1005: ';' expected.

3033     M[Key] extends AnyFunction ? never
                ~~~~~~~

node_modules/sequelize/dist/lib/model.d.ts:3034:37 - error TS1005: ';' expected.

3034     : { [NonAttributeBrand]: true } extends M[Key] ? never
                                         ~~~~~~~
```
(etc.)

[sequelize 6.14.0]: https://github.com/sequelize/sequelize/releases/tag/v6.14.0